--
-- PostgreSQL database dump
--

\restrict vYkr2ivMRwnb8nv9XJghFd8J4lEVbBb3wYQtdRusB4LJOJhgXS6R6JGYhAc6F84

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: books; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.books (
    id bigint NOT NULL,
    author character varying(100) NOT NULL,
    description character varying(200) NOT NULL,
    page_count integer,
    publisher character varying(100),
    synopsis character varying(200) NOT NULL,
    title character varying(200) NOT NULL,
    type character varying(100)
);


ALTER TABLE public.books OWNER TO "user";

--
-- Name: books_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: books; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.books (id, author, description, page_count, publisher, synopsis, title, type) FROM stdin;
36	Jane Austen	A classic tale of love and misunderstanding	432	Penguin Classics	The story of Elizabeth Bennet and Mr. Darcy's tumultuous relationship.	Pride and Prejudice	ROMANCE
37	Diana Gabaldon	A time-travel romance set in Scotland	850	Delacorte Press	A WWII nurse travels back in time to 1743 Scotland.	Outlander	ROMANCE
11	Eric Evans	Tackling complexity in the heart of software	560	Addison-Wesley	Not just a book about object-oriented design, but a comprehensive guide to building complex software systems.	Domain-Driven Design	TECHNICAL
12	Robert C. Martin	A guide to writing readable, maintainable code	464	Prentice Hall	Even bad code can function. But if code isn't clean, it can bring a development organization to its knees.	Clean Code: A Handbook of Agile Software Craftsmanship	TECHNICAL
13	Andrew Hunt, David Thomas	Your journey to mastery	352	Addison-Wesley	This book covers topics ranging from personal responsibility and career development to architectural techniques.	The Pragmatic Programmer	TECHNICAL
14	Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides	The classic book on design patterns	395	Addison-Wesley	Capturing a wealth of experience about the design of object-oriented software.	Design Patterns: Elements of Reusable Object-Oriented Software	TECHNICAL
15	Martin Fowler	How to improve existing code structure	461	Addison-Wesley	The process of changing a software system in such a way that it does not alter the external behavior of the code.	Refactoring: Improving the Design of Existing Code	TECHNICAL
16	Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein	The comprehensive guide to algorithms	1292	MIT Press	Covers a broad range of algorithms in depth.	Introduction to Algorithms	TECHNICAL
17	Harold Abelson, Gerald Jay Sussman	Classic computer science textbook	657	MIT Press	Focuses on the idea that a computer language is primarily a formal medium for expressing ideas about methodology.	Structure and Interpretation of Computer Programs	TECHNICAL
18	Frederick P. Brooks Jr.	Essays on software engineering	322	Addison-Wesley	The classic book on the human elements of software engineering.	The Mythical Man-Month	TECHNICAL
19	Steve McConnell	A comprehensive guide to software construction	914	Microsoft Press	Widely considered one of the best practical guides to programming.	Code Complete: A Practical Handbook of Software Construction	TECHNICAL
20	Kyle Simpson	Deep dive into JavaScript mechanisms	278	O'Reilly	This series dives into trickier parts of the JavaScript language.	You Don't Know JS	TECHNICAL
21	Robert C. Martin	A code of conduct for professional programmers	210	Prentice Hall	How to behave as a true software craftsman.	The Clean Coder	TECHNICAL
22	Michael Feathers	Techniques for working with legacy systems	456	Prentice Hall	Practical techniques for getting legacy code under control.	Working Effectively with Legacy Code	TECHNICAL
23	Joshua Bloch	Best practices for Java programming	416	Addison-Wesley	A must-have for every Java developer.	Effective Java	TECHNICAL
24	Gene Kim, Kevin Behr, George Spafford	A novel about IT, DevOps, and helping your business win	345	IT Revolution Press	A novel that teaches the principles of DevOps.	The Phoenix Project	TECHNICAL
25	Betsy Beyer, Chris Jones, Jennifer Petoff, Niall Richard Murphy	How Google runs production systems	550	O'Reilly	How Google implements, measures, and maintains reliability.	Site Reliability Engineering	TECHNICAL
26	Kent Beck	Learn TDD through practical examples	240	Addison-Wesley	Teaches Test-Driven Development through examples.	Test-Driven Development: By Example	TECHNICAL
27	Jon Bentley	Classic programming problems and solutions	256	Addison-Wesley	A collection of essays about programming and programming techniques.	Programming Pearls	TECHNICAL
28	Donald E. Knuth	The comprehensive reference for algorithms	650	Addison-Wesley	Monumental work covering fundamental algorithms.	The Art of Computer Programming	TECHNICAL
29	Douglas Crockford	The subset of JavaScript that's worth using	176	O'Reilly	A book about the good parts of JavaScript.	JavaScript: The Good Parts	TECHNICAL
30	Brian W. Kernighan, Dennis M. Ritchie	The classic book on C programming	272	Prentice Hall	The definitive guide to C programming.	The C Programming Language	TECHNICAL
31	Eric Freeman, Elisabeth Robson, Bert Bates, Kathy Sierra	A brain-friendly guide to design patterns	694	O'Reilly	Uses a visually rich format designed for the way your brain works.	Head First Design Patterns	TECHNICAL
32	Jez Humble, David Farley	Reliable software releases through build, test, and deployment automation	512	Addison-Wesley	A revolutionary approach to software delivery.	Continuous Delivery	TECHNICAL
33	Gene Kim, Jez Humble, Patrick Debois, John Willis	How to create world-class agility, reliability, & security	480	IT Revolution Press	A practical guide to DevOps principles.	The DevOps Handbook	TECHNICAL
34	Sam Newman	Designing fine-grained systems	280	O'Reilly	A comprehensive overview of microservices.	Building Microservices	TECHNICAL
35	Larry L. Peterson, Bruce S. Davie	A systems approach	920	Morgan Kaufmann	Comprehensive textbook on computer networking.	Computer Networks	TECHNICAL
38	Nicholas Sparks	A touching love story that spans decades	214	Warner Books	The story of Noah and Allie's enduring love.	The Notebook	ROMANCE
39	Charlotte Brontë	A Gothic romance and coming-of-age story	532	Smith, Elder & Co.	The story of Jane Eyre's moral and spiritual development.	Jane Eyre	ROMANCE
40	Jojo Moyes	A story of love and difficult choices	369	Penguin Books	A young woman becomes a caregiver for a paralyzed man.	Me Before You	ROMANCE
41	Audrey Niffenegger	A love story complicated by time travel	546	MacAdam/Cage	Henry has a genetic disorder that causes him to time travel.	The Time Traveler's Wife	ROMANCE
42	Margaret Mitchell	An epic romance set during the Civil War	1037	Macmillan Publishers	The turbulent romance between Scarlett O'Hara and Rhett Butler.	Gone with the Wind	ROMANCE
43	Sally Thorne	A contemporary workplace romance	384	William Morrow	Two executive assistants who hate each other are up for the same promotion.	The Hating Game	ROMANCE
44	Helen Fielding	A modern romantic comedy	288	Picador	Bridget Jones navigates love and life in London.	Bridget Jones's Diary	ROMANCE
45	Emily Brontë	A passionate and tragic love story	464	Thomas Cautley Newby	The intense, doomed love between Catherine Earnshaw and Heathcliff.	Wuthering Heights	ROMANCE
46	Elena Armas	A fake dating romance	512	Atria Books	Catalina needs a date to her sister's wedding in Spain.	The Spanish Love Deception	ROMANCE
47	Casey McQuiston	A romance between the First Son and a Prince	421	St. Martin's Griffin	The First Son of the United States falls for the Prince of Wales.	Red, White & Royal Blue	ROMANCE
48	Ali Hazelwood	A fake dating academic romance	384	Berkley	A PhD student fakes a relationship with a young professor.	The Love Hypothesis	ROMANCE
49	Graeme Simsion	A unique love story about a genetics professor	304	Text Publishing	A genetics professor creates a questionnaire to find the perfect wife.	The Rosie Project	ROMANCE
50	Taylor Jenkins Reid	A Hollywood romance spanning decades	389	Atria Books	Aging Hollywood icon reveals the truth about her seven marriages.	The Seven Husbands of Evelyn Hugo	ROMANCE
51	Emily Henry	Two friends who take vacations together	364	Berkley	Best friends who take a trip together every summer.	People We Meet on Vacation	ROMANCE
52	Emily Henry	Two writers with opposite genres fall in love	384	Berkley	A romance writer and a literary fiction author swap genres.	Beach Read	ROMANCE
53	Helen Hoang	An autistic econometrician hires an escort	333	Berkley	Stella Lane decides to hire a male escort to teach her about relationships.	The Kiss Quotient	ROMANCE
54	Colleen Hoover	A complex love story with difficult themes	384	Atria Books	Lily's relationship with Ryle is challenged when her first love reappears.	It Ends with Us	ROMANCE
55	Julia Quinn	The first book in the Bridgerton series	384	Avon	Daphne Bridgerton's fake courtship with the Duke of Hastings.	The Duke and I	ROMANCE
56	Stephenie Meyer	A human girl falls in love with a vampire	498	Little, Brown	Bella Swan moves to Forks and falls in love with Edward Cullen.	Twilight	ROMANCE
57	Jasmine Guillory	A fake date turns into something real	320	Berkley	A lawyer and a doctor strike up a conversation in an elevator.	The Wedding Date	ROMANCE
58	André Aciman	A summer romance in Italy	256	Farrar, Straus and Giroux	Seventeen-year-old Elio falls for Oliver, a graduate student.	Call Me by Your Name	ROMANCE
59	Beth O'Leary	Two people share an apartment and communicate via notes	400	Quercus	Tiffy and Leon share a flat but have never met.	The Flatshare	ROMANCE
60	Sarah J. Maas	A fantasy romance series	432	Bloomsbury	Feyre is taken to a magical land for killing a faerie.	A Court of Thorns and Roses	ROMANCE
61	Robert Louis Stevenson	A classic pirate adventure story	311	Cassell and Company	Young Jim Hawkins finds a treasure map and sets sail.	Treasure Island	ADVENTURE
62	J.R.R. Tolkien	A fantasy adventure in Middle-earth	310	George Allen & Unwin	Bilbo Baggins joins a quest to reclaim treasure from a dragon.	The Hobbit	ADVENTURE
63	Mark Twain	A journey down the Mississippi River	366	Chatto & Windus	Huck Finn's adventures with the runaway slave Jim.	The Adventures of Huckleberry Finn	ADVENTURE
64	Jules Verne	An underwater adventure	360	Pierre-Jules Hetzel	Professor Aronnax's journey aboard the Nautilus.	Twenty Thousand Leagues Under the Sea	ADVENTURE
65	Michael Crichton	A dinosaur theme park gone wrong	448	Alfred A. Knopf	Scientists create a theme park with cloned dinosaurs.	Jurassic Park	ADVENTURE
66	Yann Martel	A survival story at sea	326	Knopf Canada	A boy survives a shipwreck in a lifeboat with a Bengal tiger.	Life of Pi	ADVENTURE
67	Jack London	A dog's adventure in the Yukon	232	Macmillan	Buck, a domesticated dog, becomes a sled dog in Alaska.	The Call of the Wild	ADVENTURE
68	Jules Verne	A race against time	187	Pierre-Jules Hetzel	Phileas Fogg attempts to circumnavigate the world in 80 days.	Around the World in Eighty Days	ADVENTURE
69	Gary Paulsen	A boy's survival in the Canadian wilderness	208	Bradbury Press	Brian Robeson survives a plane crash with only a hatchet.	Hatchet	ADVENTURE
70	Daniel Defoe	A man's survival on a deserted island	320	William Taylor	Crusoe spends 28 years on a remote tropical island.	Robinson Crusoe	ADVENTURE
71	Arthur Conan Doyle	An expedition to a plateau with dinosaurs	342	Hodder & Stoughton	Professor Challenger leads an expedition to South America.	The Lost World	ADVENTURE
72	Johann David Wyss	A family's survival on a deserted island	352	Johann Rudolph Wyss	A Swiss family shipwrecked in the East Indies.	The Swiss Family Robinson	ADVENTURE
73	H. Rider Haggard	A search for a lost treasure	320	Cassell and Company	An adventure in search of the legendary diamond mines.	King Solomon's Mines	ADVENTURE
74	Alexandre Dumas	Adventures in 17th-century France	700	Baudry	The adventures of d'Artagnan and the three musketeers.	The Three Musketeers	ADVENTURE
75	Jules Verne	An expedition into a volcano	183	Pierre-Jules Hetzel	Professor Lidenbrock discovers a passage to the center of the Earth.	Journey to the Center of the Earth	ADVENTURE
76	Jack London	A wolfdog's journey in the Yukon	298	Macmillan	The story of a wild wolfdog during the Klondike Gold Rush.	White Fang	ADVENTURE
77	Homer	An epic journey home from war	541	Various	Odysseus' ten-year journey home after the Trojan War.	The Odyssey	ADVENTURE
78	Alexandre Dumas	A tale of revenge and adventure	1276	Pétion	Edmond Dantès' escape from prison and his quest for revenge.	The Count of Monte Cristo	ADVENTURE
79	Herman Melville	A whaling adventure and obsession	635	Richard Bentley	Captain Ahab's obsessive quest for the white whale.	Moby-Dick	ADVENTURE
80	Mark Twain	A boy's adventures in Missouri	274	American Publishing Company	Tom Sawyer's adventures along the Mississippi River.	The Adventures of Tom Sawyer	ADVENTURE
81	J.R.R. Tolkien	An epic fantasy adventure	1178	George Allen & Unwin	Frodo Baggins' quest to destroy the One Ring.	The Lord of the Rings	ADVENTURE
82	William Goldman	A fantasy adventure with romance	398	Harcourt Brace Jovanovich	A farmhand must rescue his true love.	The Princess Bride	ADVENTURE
83	C.S. Lewis	A nautical adventure in Narnia	223	Geoffrey Bles	A voyage to the edge of the world in Narnia.	The Voyage of the Dawn Treader	ADVENTURE
84	Jon Krakauer	A young man's adventure into the Alaskan wilderness	207	Villard Books	The true story of Christopher McCandless.	Into the Wild	ADVENTURE
85	Suzanne Collins	A survival competition in a dystopian future	374	Scholastic Press	Katniss Everdeen fights for survival in the annual Hunger Games.	The Hunger Games	ADVENTURE
86	Harper Lee	A story of racial injustice in the American South	281	J. B. Lippincott & Co.	Scout Finch's father defends a black man accused of rape.	To Kill a Mockingbird	DRAMA
87	F. Scott Fitzgerald	A critique of the American Dream	180	Charles Scribner's Sons	Jay Gatsby's obsession with Daisy Buchanan.	The Great Gatsby	DRAMA
88	George Orwell	A dystopian novel about totalitarianism	328	Secker & Warburg	Winston Smith rebels against a totalitarian regime.	1984	DRAMA
89	J.D. Salinger	A teenager's journey through New York City	277	Little, Brown	Holden Caulfield's experiences after being expelled.	The Catcher in the Rye	DRAMA
90	Khaled Hosseini	A story of friendship and redemption in Afghanistan	371	Riverhead Books	Amir's journey to redeem himself after betraying his friend.	The Kite Runner	DRAMA
91	Khaled Hosseini	The lives of two Afghan women	384	Riverhead Books	Mariam and Laila's friendship in war-torn Afghanistan.	A Thousand Splendid Suns	DRAMA
92	Markus Zusak	A girl's love of books in Nazi Germany	584	Picador	Liesel Meminger steals books during WWII.	The Book Thief	DRAMA
93	Donna Tartt	A group of classics students and a murder	559	Alfred A. Knopf	Six students at an elite college become involved in a murder.	The Secret History	DRAMA
94	Sylvia Plath	A woman's descent into mental illness	244	Heinemann	Esther Greenwood's internship in New York City.	The Bell Jar	DRAMA
95	Hanya Yanagihara	The lives of four friends in New York City	720	Doubleday	Four college friends navigate adulthood in New York.	A Little Life	DRAMA
96	Oscar Wilde	A man's portrait ages while he remains young	254	Lippincott's Monthly Magazine	Dorian Gray remains youthful while his portrait ages.	The Picture of Dorian Gray	DRAMA
97	Gabriel García Márquez	The multi-generational story of the Buendía family	417	Editorial Sudamericana	The magical realist tale of Macondo and its founding family.	One Hundred Years of Solitude	DRAMA
98	Margaret Atwood	A dystopian novel about a theocratic society	311	McClelland and Stewart	Offred's life as a handmaid in the Republic of Gilead.	The Handmaid's Tale	DRAMA
99	Donna Tartt	A boy's life after a museum bombing	771	Little, Brown	Theo Decker survives a terrorist attack at a museum.	The Goldfinch	DRAMA
100	Sally Rooney	The complicated relationship between two Irish teenagers	266	Faber & Faber	Connell and Marianne's on-again, off-again relationship.	Normal People	DRAMA
101	Stephen King	A shape-shifting clown terrorizes a town	1138	Viking Press	Seven children are terrorized by an evil entity that exploits their fears.	It	HORROR
102	Stephen King	A family's terrifying experience in a haunted hotel	447	Doubleday	Jack Torrance becomes the winter caretaker of the Overlook Hotel.	The Shining	HORROR
103	Mary Shelley	A scientist creates a sentient creature	280	Lackington, Hughes, Harding, Mavor & Jones	Victor Frankenstein creates a creature in an unorthodox experiment.	Frankenstein	HORROR
104	Bram Stoker	The classic vampire novel	418	Archibald Constable and Company	Count Dracula's attempt to move from Transylvania to England.	Dracula	HORROR
105	Shirley Jackson	A psychological horror story	246	Viking Press	Four people stay in a notoriously haunted house.	The Haunting of Hill House	HORROR
106	William Peter Blatty	A girl possessed by a demonic entity	340	Harper & Row	A mother seeks help for her possessed daughter.	The Exorcist	HORROR
107	Stephen King	A burial ground that brings the dead back to life	374	Doubleday	A doctor discovers an ancient burial ground behind his home.	Pet Sematary	HORROR
108	Thomas Harris	A psychological thriller about a serial killer	338	St. Martin's Press	Clarice Starling interviews Hannibal Lecter to catch another killer.	The Silence of the Lambs	HORROR
109	Josh Malerman	Creatures that cause madness when seen	262	Ecco Press	A mother must guide her children through a world where looking outside is deadly.	Bird Box	HORROR
110	Henry James	A Gothic ghost story	131	Macmillan	A governess cares for two children in a remote estate.	The Turn of the Screw	HORROR
\.


--
-- Name: books_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.books_id_seq', 110, true);


--
-- Name: books books_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict vYkr2ivMRwnb8nv9XJghFd8J4lEVbBb3wYQtdRusB4LJOJhgXS6R6JGYhAc6F84

